AOSC-Dev/oma

src/lang.rs
To workaround microsoft/terminal#16574.
=> fix(lang): disable bidirectional isolation in Fluent

Cargo.toml, oma-console/Cargo.toml, oma-contents/Cargo.toml, oma-fetch/Cargo.toml, oma-history/Cargo.toml, oma-pm-operation-type/Cargo.toml, oma-pm/Cargo.toml, oma-refresh/Cargo.toml, oma-topics/Cargo.toml, oma-utils/Cargo.toml
Unless a module is mostly useful for oma, I have described them as general- purpose crates; otherwise, I have marked them as "used by oma," to avoid potential confusion whilst suggesting that the crate can still be useful for other projects.
=> chore: refine descriptions for each crate

Cargo.lock, Cargo.toml, oma-console/Cargo.toml, oma-console/src/lib.rs, oma-utils/Cargo.toml, oma-utils/src/oma/mod.rs, src/lang.rs
This change breaks rustc < 1.80.0 compilation
=> chore!: use `std::sync::LazyLock` to replace `once_cell::sync::Lazy`

Cargo.toml, oma-pm/Cargo.toml, oma-pm/src/apt.rs
If `foo` is already installed, by default apt does not install its recommends when running install (even in the case of `--reinstall`) oma will install the recommends if the user does not specify `--no-install-recommends`, or if the configuration file for apt is modified
This change is for AOSC OS only
=> feat(oma-pm): allow `oma install foo` will also install recommends

data/apt.conf.d/50oma.conf
`apt update` deletes BinContents created by `oma refresh`, so let `apt update` download it and it won't be deleted.
=> chore: make `apt update` download `BinContents`

data/apt.conf.d/50oma.conf
This will allow users who do not have apt-file installed but have oma installed to use apt update to download to the Contents file.
=> chore: add download contents option to apt config file

src/args.rs
- `install` add alias `add`
- `remove` add alias `rm`, `del` and remove `delete`
- `upgrade` remove alias `dist-upgrade` (avoiding misunderstandings)
=> feat: adjust subcmd alias

.github/workflows/create-pull-request.yml
Use tilde (~) to denote pre-release, allowing users to upgrade to a final release later.
=> chore(.github): use tilde to replace dash-suffix in DPKG_VER

oma-console/Cargo.toml, oma-console/src/pager.rs
`console::measure_text_width` will strip ansi escape code
=> fix(oma-console): use `console::measure_text_width` to calculate termininal width on pager

Cargo.lock, oma-console/Cargo.toml, src/main.rs
`async-std` and `tokio` stdin use `spawn_blocking` to handle `stdin`, That is, `stdin` task does not end after the timeout, so no input can be processed after opening the TUI.
This fix came from upstream: https://github.com/dalance/termbg/tree/non_blocking_stdin, but it was not adopted by upstream because it doesn't compile under Windows, but fortunately oma has no plans to support Windows for the time being.
ref:
- https://github.com/tokio-rs/tokio/issues/5535
- https://github.com/async-rs/async-std/issues/1055
- https://github.com/zellij-org/zellij/issues/538
- https://github.com/zellij-org/zellij/blob/3569daf7c9cacc1dbbec6a3813079130b4c0683c/zellij-client/src/os_input_output.rs#L270
=> fix(oma-console): fix termbg timeout will blocking stdin

data/installer/get-oma.sh
Enable Ubuntu 24.10, add deepin V23 and openKylin 2.0 as we deploy the new repo signing key on October 7, 2024.
=> get-oma.sh: add more distributions

oma-history/src/lib.rs, oma-pm-operation-type/src/lib.rs, oma-pm/src/apt.rs, src/subcommand/upgrade.rs, src/subcommand/utils.rs, src/table.rs
... It seems that executing `new_cache!()` immediately after the commit completes triggers a race condition, so I've changed the logic for getting autoremovable, which may also be faster since it doesn't need to reload the cache.
=> fix(oma-pm)!: try to fix install after oma will return `LZMA: write failed`

oma-pm/src/apt.rs, src/args.rs, src/main.rs, src/subcommand/topics.rs, src/subcommand/upgrade.rs, src/tui/mod.rs
`--no-remove` like `apt upgrade`
=> feat(oma-pm)!: add `oma upgrade` option for non-AOSC OS targets

README.md
To make the `Dependencies` section closer to the `Build from source` subsection.
=> chore(README): move the Dependencies section below the Installation section

Cargo.lock, apt-auth-config/Cargo.toml, apt-auth-config/src/lib.rs, oma-fetch/src/download.rs, oma-fetch/src/lib.rs, oma-pm-operation-type/src/lib.rs, oma-pm/examples/download_pkgs.rs, oma-pm/examples/install_fish.rs, oma-pm/src/apt.rs, oma-pm/src/commit.rs, oma-pm/src/download.rs, oma-refresh/src/db.rs, oma-refresh/src/sourceslist.rs, src/error.rs, src/subcommand/download.rs, src/subcommand/fix_broken.rs, src/subcommand/history.rs, src/subcommand/install.rs, src/subcommand/mirror.rs, src/subcommand/pick.rs, src/subcommand/refresh.rs, src/subcommand/remove.rs, src/subcommand/topics.rs, src/subcommand/upgrade.rs, src/subcommand/utils.rs, src/tui/mod.rs
=> refactor `apt-auth-config`

Cargo.lock, oma-history/Cargo.toml, oma-history/src/lib.rs, oma-history/src/migrations.rs, oma-pm-operation-type/Cargo.toml, oma-pm-operation-type/src/lib.rs, oma-pm/src/apt.rs, src/error.rs, src/main.rs, src/subcommand/fix_broken.rs, src/subcommand/history.rs, src/subcommand/install.rs, src/subcommand/list.rs, src/subcommand/pick.rs, src/subcommand/remove.rs, src/subcommand/topics.rs, src/subcommand/upgrade.rs, src/subcommand/utils.rs, src/table.rs, src/tui/mod.rs, src/utils.rs
The old `oma history` output had titles that didn't necessarily describe what they did, e.g. changes made via `oma tui` were attributed to “Changes”, how should we redesign the titles in the menu? This will also affect how some fields are stored in the database
The new `oma history` will be more flexible and have more possible ways of querying the data the user wants, do we need to categorize some of the common queries into subcommands in `oma history`?
How should I migrate from the old table to the new one?
=> Refactor `oma-history` database

Cargo.toml, src/args.rs, src/subcommand/mod.rs
In environments such as 2k0300, `oma mirror` will not be available, so for the convenience of users for this purpose, `oma mirror` is listed as a separate `mirror` feature.
=> chore: split `oma mirror` from aosc feature

data/config/oma-debian.toml, data/config/oma.toml
- Drop meaningless no_refresh_topics for Debian derivatives.
- Make comments more descriptive (and grammatically correct).
=> chore(data/config): lint oma configuration files

.github/workflows/create-pull-request.yml
The last implementation checked for a local `oma-preview' branch with `git rev-parse', this is not correct as that branch was never checked out. This caused the workflow to create a new `oma-preview' branch unconditionally, destroying previous history in that process.
Also, rebased branches must be pushed forcefully, so specify `--force' with the push command.
=> ci: fix check for oma-preview branch existence, rebase-push logic

.github/workflows/deb_amd64.yml, .github/workflows/deb_arm64.yml
```
Compiling oma v1.21.0-rc.1 (/oma)
error: linking with `cc` failed: exit status: 1
|
= note:  "cc" "-m64" "/tmp/rustcfbIfcK/symbols.o" "<359 object files omitted>" "-Wl,--as-needed" "-Wl,-Bstatic" "/tmp/rustcfbIfcK/{liboma_apt-b2e6e1fb7ca27be7.rlib,libcxx-bf91f6f2fd4e9cac.rlib,liblink_cplusplus-1de963ed9e61a14e.rlib,liblibsqlite3_sys-3c26806c9b57f725.rlib,libring-d159ed07f1c3fa49.rlib,libzstd_sys-6693a21698c7deac.rlib,liblzzzz-4c1698d662505cbd.rlib}.rlib" "<sysroot>/lib/rustlib/x86_64-unknown-linux-gnu/lib/{libcompiler_builtins-*}.rlib" "-Wl,-Bdynamic" "-lnettle" "-lhogweed" "-lgmp" "-lapt-pkg" "-lstdc++" "-llzma" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-L" "/tmp/rustcfbIfcK/raw-dylibs" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" …
```
=> ci: temporary not publish debian11 package
