AOSC-Dev/oma

oma-refresh/src/util.rs
Transliterate `_` in dist as `%5f` in list archive, in accordance with APT behaviour.
=> Fix underscore transliteration

oma-pm/src/apt.rs
Thanks to @Veetaha suggestion!
=> refactor(oma-pm): improve `OmaApt::summary` logic

Cargo.lock, Cargo.toml, oma-pm/src/apt.rs, src/subcommand/tui.rs
- update ratatui to v0.28.1
- downgrade tabled to v0.15.0 (make ratatui v0.28 happy)
=> chore: update all deps

i18n/en-US/oma.ftl, i18n/zh-CN/oma.ftl, i18n/zh-TW/oma.ftl, src/subcommand/contents_find.rs, src/subcommand/depends.rs, src/subcommand/download.rs, src/subcommand/history.rs, src/subcommand/install.rs, src/subcommand/mark.rs, src/subcommand/rdepends.rs, src/subcommand/remove.rs, src/subcommand/show.rs, src/subcommand/upgrade.rs, src/subcommand/utils.rs
=> feat: `oma install/...` handle no result add cmd from package tips

oma-console/src/pager.rs
implement for https://github.com/AOSC-Dev/oma/issues/166
Support pattern search in tui
- "N"/"n" for next pattern
- press "/" to enter search mode
=> feat: support pattern search in tui

data/completions/oma.bash, data/completions/oma.fish, src/args.rs
- Also fix `oma purge --force-unsafe-io`
=> feat: update completions

oma-console/src/pager.rs
Previously, the h/j/k/l (Vim-like arrow keys) and q keys conflicted with search mode inputs. Exclude said keybindings whilst in search mode.
=> fix(oma-console): fix key conflict in pager search mode

README.md
fix label jump of `installation`
=> fix(doc): fix readme installation label

CHANGELOG.md, CONTRIBUTING.md, oma-contents/CHANGELOG.md, oma-fetch/src/download.rs
Found via `codespell -L crate,ratatui,ans,bu`
=> chores: fix typos

oma-console/src/pager.rs
This adds support for navigating to the last page with End key and to the first page with Home key.
=> feat(oma-console): support navigating with Home/End keys

data/installer/get-oma.sh
add linux mint 22.1(Xia) support,which is based on noble.
=> fix(installer): add linux mint 22.1(Xia) detection

src/tui/state.rs
in `oma tui`, [TAB] -> [Dn] will panic
=> fix(tui): fix some edge case will panic

oma-console/src/pager.rs
=> feat(oma-console): add <space> f/b to PgDn/PgUp

oma-refresh/src/db.rs
=> fix(oma-refresh): flat repo should not check Date

src/subcommand/command_not_found.rs, src/subcommand/mirror.rs, src/table.rs
This reverts commit 0201a136d2864a70e37257e94325275525df397d.
=> Revert "feat: limit tum table width length (#380)"

Cargo.toml, oma-pm/src/apt.rs, oma-pm/src/commit.rs, oma-pm/src/dbus.rs, oma-pm/src/lib.rs, oma-pm/src/pkginfo.rs, oma-pm/src/progress.rs, src/subcommand/show.rs, src/subcommand/utils.rs
- Add key highlight
- Use apt `RecordField` to display value, improve performance
- Add display Provides support
=> feat(show)!: refactor `oma show` output

Cargo.lock, Cargo.toml, src/subcommand/command_not_found.rs, src/subcommand/mirror.rs, src/table.rs
~https://github.com/zhiburt/tabled/issues/526#issuecomment-2809966659 wait tabled release~
=> Reapply "feat: limit tum table width length (#380)" (#388)

oma-console/src/pager.rs, src/tui/tui_inner.rs
<kbd>Alt</kbd> + <kbd>d</kbd>         -- Delete until start of next word
<kbd>Control</kbd> + <kbd>w</kbd>     -- Delete until end of last word
<kbd>Control</kbd> + <kbd>Right</kbd> -- Jump to start of next word
<kbd>Control</kbd> + <kbd>Left</kbd>  -- Jump to end of last word
<kbd>Control</kbd> + <kbd>p</kbd>     -- Go to previous line
<kbd>Control</kbd> + <kbd>n</kbd>     -- Go to next line
=> feat(tui,pager): add several keybinds

data/policykit/io.aosc.oma.apply.policy
- **fix(polkit): update PolicyKit exec path for oma**
- **chore(polkit): change auth_admin_keep to auth_admin**
=> Some polkit related minor fixes

oma-refresh/src/db.rs, oma-refresh/src/sourceslist.rs, oma-refresh/src/util.rs
=> fix(oma-refresh): handle if url ends with '/'
